version: '3.8'

services:
  tts-service:
    build:
      context: .
      dockerfile: Dockerfile.coreml
    platform: linux/arm64
    ports:
      - "5005:5005"
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2.0'
        reservations:
          memory: 768M
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Increased for CoreML initialization
    restart: unless-stopped
    volumes:
      # Optional: Mount for model caching
      - ./models:/app/models:ro