version: '3.8'

services:
  tts-service:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    ports:
      - "5005:5005"
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Increased for GPU initialization
    restart: unless-stopped
    volumes:
      # Optional: Mount for model caching
      - ./models:/app/models:ro